### DISCUSSION TITLE
Using "{{text}}" as an alternate highlight

### DISCUSSION THREAD

**Discussion by dmantisk** [Mara-Li/obsidian-regex-mark#20] [Show and tell]
The reason I made this is for the 'Spaced repetition' plugin's cloze feature.
This allows me to highlight things with or without making them a cloze.

### The Tags
![image](https://github.com/user-attachments/assets/e0be4298-91eb-4c97-ba6d-6df835724b66)
Opening : `\[open:(.*?)\]`
Closing : `\[close:(.*?)\]`

### The Regex
![image](https://github.com/user-attachments/assets/75155b5c-16d8-4daa-a25c-b63fd1e264a3)
Regex : `[open:\{\{](.*)[close:\}\}]`

### The CSS Snippet
```css
.highlight2 {
    background-color: #3333aa;
	padding-left:   1px;
	padding-right:  1px;
	padding-top:    0px;
	padding-bottom: 1px;
	border-radius: 6px;
}
```
### The Results
![image](https://github.com/user-attachments/assets/59f113e8-eeb7-4e9e-b0c2-086174f434ab)
